#this local  Makefile is just provided to 
#the kbuild system of the kernel source tree
#the actual Makefile and scripts/utilities
#are handled by the kbuild system 
obj-m := proc_seq_example1.o 
#obj-m :=   kset-example.o
#ccflags-y += -DDEBUG 
#ccflags-y += -O0
ccflags-y += -g
#ccflags-y += -E
